### PR TITLE
New test-related folders for feature files

### PR DESCRIPTION
**Pull request by mafriend**
Hello!

Per the [slack conversation](https://drud.slack.com/archives/CDCDPS74M/p1539372135000100) in the testing channel, here is the first PR to add some testing-related folders to the repo and a new home for the hosting scenarios from the product feature testing outline.

Thank you!

### CODE REVIEW

**Comment by alkymst** [comment]
@mafriend this looks great. If you can get the CLA done and I'll get this merged in.

**Comment by mafriend** [comment]
Hey @alkymst ! When you say "get the CLA" done, what do you mean here? Happy to take on whatever I need to to get this merged in! 

Thanks for looking at this!

**Comment by alkymst** [comment]
The [Contributor License Agreement](https://cla-assistant.io/drud/ddev-ui?pullRequest=170) has to be accepted to merge your code into the repo.

**Comment by mafriend** [comment]
Thanks! I've signed the agreement!

**Pull request merged**
